/*
 * XenForo attachment_editor_new.min.js
 * Copyright 2010-2017 XenForo Ltd.
 * Released under the XenForo License Agreement: http://xenforo.com/license-agreement
 */
(function(g,n,o){var l=XenForo.speed.normal,i=XenForo.speed.fast;XenForo.AttachmentUploader=function(c){var e=g(c.data("trigger"));c.closest("form");var a={},b=function(a,b,d){(b=c.data("err-"+b)||d)||(b=c.data("err-unknown"));a?XenForo.alert(b+"<br /><br />"+XenForo.htmlspecialchars(a.name)):XenForo.alert(b)},d=c.data("maxfilesize");c.data("maxuploads");var f=c.data("extensions"),m=c.data("uniquekey"),f=f.replace(/[;*.]/g,"").replace(/,{2,}/g,",").replace(/^,+/,"").replace(/,+$/,"");c.show();var h,
j=n.Flow?!0:!1,k=navigator.userAgent;if(k.match(/Android [1-4]/)&&(k=k.match(/Chrome\/([0-9]+)/),!k||parseInt(k[1],10)<33))console.log("Old Android WebView detected. Must fallback to basic uploader."),j=!1;if(j){var i=!1,j={target:c.data("action"),allowDuplicateUploads:!0,fileParameterName:c.data("postname"),query:function(){var b=g.extend({_xfToken:XenForo._csrfToken,_xfNoRedirect:1,_xfResponseType:i?"json-text":"json"},a);c.find(".HiddenInput").each(function(a,d){var c=g(d);b[c.data("name")]=c.data("value")});
return b},simultaneousUploads:1,testChunks:!1,chunkSize:4294967296,readFileFn:function(a,b,c,d,f){var g="slice";a.file.slice?g="slice":a.file.mozSlice?g="mozSlice":a.file.webkitSlice&&(g="webkitSlice");d||(d="");f.readFinished(a.file[g](b,c,d))}};h=new Flow(j);h.support||(h=new FustyFlow(j),i=!0);j=g("<span />").insertAfter(e).append(e);h.assignBrowse(j[0],!1,!1,{accept:"."+f.toLowerCase().replace(/,/g,",.")});i?(f=e.outerWidth(),f>30&&j.css("width",f)):(f=j.find("input[type=file]"),f.css("overflow",
"hidden"),f.css(XenForo.isRTL()?"right":"left",-1E3));e.on("click BeforeOverlayTrigger",function(a){a.preventDefault()});h.on("fileAdded",function(a){var f=!1;a.id=a.uniqueIdentifier;switch(a.name.substr(a.name.lastIndexOf(".")).toLowerCase()){case ".jpg":case ".jpeg":case ".jpe":case ".png":case ".gif":f=!0}var e=g.Event("AttachmentQueueValidation");e.file=a;e.flow=h;e.isImage=f;c.trigger(e);if(e.isDefaultPrevented())return!1;if(a.size>d&&!f)return b(a,110),!1;e=g.Event("AttachmentQueued");e.file=
a;e.flow=h;e.isImage=f;c.trigger(e)});h.on("filesSubmitted",function(){h.upload()});h.on("fileProgress",function(a){a.id=a.uniqueIdentifier;c.trigger({type:"AttachmentUploadProgress",file:a,bytes:Math.round(a.progress()*a.size),flow:h})});h.on("fileSuccess",function(a,b){try{i&&b.substr(0,1)=="<"&&(b=g(g.parseHTML(b)).text());var d=g.parseJSON(b)}catch(f){console.warn(f);return}a.id=a.uniqueIdentifier;d.error?c.trigger({type:"AttachmentUploadError",file:a,ajaxData:d,flow:h}):c.trigger({type:"AttachmentUploaded",
file:a,ajaxData:d,flow:h})});h.on("fileError",function(a,b){a.id=a.uniqueIdentifier;c.trigger({type:"AttachmentUploadError",file:a,errorCode:0,message:b,ajaxData:{error:[c.data("err-unknown")]},flow:h})})}else console.error("flow.js must be loaded");g(o).bind("AutoInlineUploadComplete",function(a){if(m&&a.ajaxData&&m!==a.ajaxData.key)return!1;if(g(a.target).is("form.AttachmentUploadForm"))return e.overlay()&&e.overlay().close(),c.trigger({type:"AttachmentUploaded",ajaxData:a.ajaxData}),!1});return{getSwfUploader:function(){return null},
getFlowUploader:function(){return h},swfAlert:b,attachmentErrorAlert:b}};XenForo.AttachmentEditor=function(c){this.setVisibility=function(a){var b=c.closest(".ctrlUnit"),d=c.find(".AttachmentInsertAllBlock"),f=c.find(".AttachedFile:not(#AttachedFileTemplate)"),e=f.filter(".AttachedImage");console.log("Attachments changed, total files: %d, images: %d",f.length,e.length);b.length==0&&(b=c);a===!0?f.length?(e.length>1?d.show():d.hide(),b.show()):b.hide():f.length?(e.length>1?b.is(":hidden")?d.show():
d.xfFadeDown(XenForo.speed.fast):b.is(":hidden")?d.hide():d.xfFadeUp(XenForo.speed.fast,!1,XenForo.speed.fast,"swing"),b.xfFadeDown(XenForo.speed.normal)):(d.slideUp(XenForo.speed.fast),b.xfFadeUp(XenForo.speed.normal,!1,!1,"swing"))};this.setVisibility(!0);g("#AttachmentUploader").bind({click:function(){g("textarea.BbCodeWysiwygEditor").each(function(){var a=g(this).data("XenForo.BbCodeWysiwygEditor");a&&a.blurEditor()})},AttachmentQueued:function(a){var b=a.file,d=b.uniqueIdentifier||b.id;console.info("Queued file %s (%d bytes).",
b.name,b.size);var f=g("#AttachedFileTemplate").clone().attr("id",d);f.find(".Filename").text(b.name);f.find(".ProgressCounter").text("0%");f.find(".ProgressGraphic span").css("width","0%");a.isImage&&f.addClass("AttachedImage");f.xfInsert("appendTo",".AttachmentList.New",null,l);f.find(".AttachmentCanceller").css("display","block").click(function(){a.swfUpload?a.swfUpload.cancelUpload(a.file.id):b.flowObj&&b.cancel();f.xfRemove(null,function(){c.trigger("AttachmentsChanged")},i,"swing")});c.trigger("AttachmentsChanged")},
AttachmentUploadProgress:function(a){var b=a.file,a=a.bytes,d=b.uniqueIdentifier||b.id;console.log("Uploaded %d/%d bytes.",a,b.size);var b=Math.min(100,Math.ceil(a*100/b.size)),a=b+"%",d=g("#"+d),c=d.find(".ProgressCounter"),e=d.find(".ProgressGraphic");c.text(a);e.css("width",a);b>=100&&d.find(".AttachmentCanceller").prop("disabled",!0).addClass("disabled");e.width()>c.outerWidth()&&c.appendTo(e)},AttachmentUploadError:function(a){var b="",d=a.file,c=d.uniqueIdentifier||d.id;g.each(a.ajaxData.error,
function(a,c){b+=c+"\n"});XenForo.alert(b+"<br /><br />"+XenForo.htmlspecialchars(d.name));var d=g("#"+c),e=d.closest(".AttachmentEditor");d.xfRemove(null,function(){e.trigger("AttachmentsChanged")},i,"swing");console.warn("AttachmentUploadError: %o",a)},AttachmentUploaded:function(a){if(a.file){var b=a.file,d=g("#"+(b.uniqueIdentifier||b.id)),e=d.find(".AttachmentText"),i=g(a.ajaxData.templateHtml),h;e.fadeOut(XenForo.speed.fast,function(){i.find(".AttachmentText").xfInsert("insertBefore",e,"fadeIn",
XenForo.speed.fast);h=d.find(".Thumbnail");h.html(i.find(".Thumbnail").html());e.xfRemove();d.attr("id","attachment"+a.ajaxData.attachment_id)})}else d=g("#attachment"+a.ajaxData.attachment_id),d.length||(d=g(a.ajaxData.templateHtml).xfInsert("appendTo",c.find(".AttachmentList.New"),null,l));c.trigger("AttachmentsChanged")}});var e=g.context(this,"setVisibility");g("#QuickReply").bind("QuickReplyComplete",function(){c.find(".AttachmentList.New li:not(#AttachedFileTemplate)").xfRemove().promise().always(e)});
c.bind("AttachmentsChanged",e)};XenForo.AttachmentInserter=function(c){c.click(function(e){var a=c.closest(".AttachedFile").find(".Thumbnail a"),b=a.data("attachmentid"),d;d=a.find("img").attr("src");a=a.attr("href");e.preventDefault();c.attr("name")=="thumb"?(e="[ATTACH]"+b+"[/ATTACH] ",d='<img src="'+d+'" class="attachThumb bbCodeImage" alt="attachThumb'+b+'" /> '):(e="[ATTACH=full]"+b+"[/ATTACH] ",d='<img src="'+a+'" class="attachFull bbCodeImage" alt="attachFull'+b+'" /> ');if(b=XenForo.getEditorInForm(c.closest("form"),
":not(.NoAttachment)"))if(b.$editor){b.insertHtml(d);var f=b.$editor.data("xenForoElastic");f&&(setTimeout(function(){f()},250),setTimeout(function(){f()},1E3))}else b.val(b.val()+e)})};XenForo.AttachmentDeleter=function(c){c.css("display","block").click(function(c){var a=g(c.target),b=a.attr("href")||a.data("href"),d=a.closest(".AttachedFile"),c=a.closest(".AttachedFile").find(".Thumbnail a").data("attachmentid");if(b){d.xfFadeUp(XenForo.speed.normal,null,i,"swing");XenForo.ajax(b,"",function(a){if(XenForo.hasResponseError(a))return d.xfFadeDown(XenForo.speed.normal),
!1;var b=d.closest(".AttachmentEditor");d.xfRemove(null,function(){b.trigger("AttachmentsChanged")},i,"swing")});if(c&&(a=XenForo.getEditorInForm(a.closest("form"),":not(.NoAttachment)"))&&a.$editor)a.$editor.find("img[alt=attachFull"+c+"], img[alt=attachThumb"+c+"]").remove(),(c=a.$editor.data("xenForoElastic"))&&c();return!1}console.warn("Unable to locate href for attachment deletion from %o",a)})};XenForo.AttachmentInsertAll=function(c){c.click(function(){g(".AttachmentInserter[name="+c.attr("name")+
"]").each(function(c,a){g(a).trigger("click")})})};XenForo.AttachmentDeleteAll=function(c){c.click(function(){g(".AttachmentDeleter").each(function(c,a){g(a).trigger("click")})})};XenForo.register(".AttachmentUploader","XenForo.AttachmentUploader");XenForo.register(".AttachmentEditor","XenForo.AttachmentEditor");XenForo.register(".AttachmentInserter","XenForo.AttachmentInserter");XenForo.register(".AttachmentDeleter","XenForo.AttachmentDeleter");XenForo.register(".AttachmentInsertAll","XenForo.AttachmentInsertAll");
XenForo.register(".AttachmentDeleteAll","XenForo.AttachmentDeleteAll")})(jQuery,this,document);
