!function($,window,document,_undefined){$(function(){var chat=$('#siropuChat');var chatElements=$('#siropuChat, #siropuChatBar');var chatBar=$('#siropuChatBar');var chatToggle=$('#siropuChatToggle');var chatContent=$('#siropuChatContent');var chatTabs=$('#siropuChatTabs');var chatMessages=$('.siropuChatMessages');var chatRooms=$('#siropuChatRooms');var chatToggleRooms=$('#siropuChatToggleRooms, .tabRooms');var chatSettings=$('#siropuChatSettings');var chatUsers=$('.siropuChatUsers');var chatLastMassage=$('#siropuChatLastMessage');var chatForumActivity=$('#siropuChatForumActivity');var chatEditor=$('#siropuChatEditor');var chatEditorBBCode=$('#siropuChatBBCode');var chatInput=chatEditor.find('input[name="message"]');var chatSubmit=$('#siropuChatSubmit');var chatAjaxURL='index.php?chat/';var chatSessionLastUpdate=0;var chatNoRoomsJoined=$('#siropuChatNoRoomsJoined');var chatSoundNew='';var chatSoundWhisper='';var chatSoundTagged='';var chatSoundBot='';var chatSoundError='';if(window.chatRefreshActiveVisible==undefined){window.chatRefreshActiveVisible=5000;}
if(window.chatRefreshActiveHidden==undefined){window.chatRefreshActiveHidden=15000;}
if(window.chatRefreshInactiveVisible==undefined){window.chatRefreshInactiveVisible=30000;}
if(window.chatRefreshInactiveHidden==undefined){window.chatRefreshInactiveHidden=60000;}
$(window).resize(function(){var roomUsers=$('#siropuChatRoom-'+window.chatRoomId+' .siropuChatMessages');if(window.matchMedia('(min-width: 800px)').matches&&roomUsers.is(':hidden')&&!chat.hasClass('siropuChatNoUsers')&&!chat.hasClass('siropuChatSidebar')){roomUsers.show();}
chatAdjustMaximizedHeight();});var chatPageTitle=$('title').text();var chatPageFocus=true;var titleBlinkInterval='';$(window).blur(function(){chatPageFocus=false;});$(window).focus(function(){chatPageFocus=true;clearInterval(titleBlinkInterval);$('title').text(chatPageTitle);});function chatGetUint($option){return $option?1:0;}
function chatGetSettings(setting){return chatGetUint(chatSettings.find('input[name="'+setting+'"]').is(':checked'));}
function chatGetSoundSettings(setting){return chatSettings.find('input[name="sound['+setting+']"]').is(':checked');}
function chatGetNotificationSettings(setting){return chatSettings.find('input[name="notification['+setting+']"]').is(':checked');}
function chatLoadSounds(soundEnabled){if(soundEnabled){var soundsDir='styles/Siropu/Chat/sounds/';chatSoundNew=chatSoundNew?chatSoundNew:new Audio(soundsDir+'alert.mp3');chatSoundWhisper=chatSoundWhisper?chatSoundWhisper:new Audio(soundsDir+'whisper.mp3');chatSoundTagged=chatSoundTagged?chatSoundTagged:new Audio(soundsDir+'tagged.mp3');chatSoundBot=chatSoundBot?chatSoundBot:new Audio(soundsDir+'bot.mp3');chatSoundError=chatSoundError?chatSoundError:new Audio(soundsDir+'error.mp3');}}
function chatSwitchTabs(roomId){$('.tabRoom-'+(roomId!==undefined?roomId:window.chatLastRoomId)).trigger('click');}
function chatDisplayNotification(data){if(!('Notification'in window)){return;}
if(!chatGetNotificationSettings(data.type)){return;}
var options={body:(data.type=='whisper'?window.chatPhrases.whisper+' ':'')+data.message,icon:$('base').attr('href')+data.icon,tag:'siropuChatNotification'};if(Notification.permission==='granted'){var notification=new Notification(window.chatPhrases.new_message,options);setTimeout(notification.close.bind(notification),window.chatDesktopNotificationsDisplayTime);}else if(Notification.permission!=='denied'){Notification.requestPermission(function(permission){if(permission==="granted"){var notification=new Notification(window.chatPhrases.new_message,options);setTimeout(notification.close.bind(notification),window.chatDesktopNotificationsDisplayTime);}});}
if(notification!==undefined){notification.onclick=function(){this.close();window.focus();if(chatBar.length&&chat.is(':hidden')){window.focus();chatBar.trigger('click');}else{chatSwitchTabs();}};}}
function chatGetLastId(el,inverse){return el.find('> li:'+(inverse?'first':'last')).attr('id');}
function chatRemoveDuplicates(el){var list=[];var data=[];if(chatGetSettings('inverse')){data=el.find('> li').slice(0,10);}else{data=el.find('> li').slice(-10);}
data.each(function(){var id=$(this).attr('id');if(list[id]){$(this).remove();}else{list[id]=true;}});}
function chatUpdateRooms(data){var inverse=chatGetSettings('inverse');for(var roomId in window.chatUserRooms){var roomTab=$('.tabRoom-'+roomId);if(data.messageActions&&data.messageActions[roomId]!==undefined){var messages=data.messageActions[roomId];for(var messageId in messages){var row=$('#siropuChatRoom-'+roomId+' .siropuChatMessages > li[id="'+messageId+'"]');var last=$('#siropuChatRoom-'+roomId+' .siropuChatMessages > li:last');switch(messages[messageId]['action']){case'prune':if(last.length&&last.find('.DateTime').data('time')<messages[messageId]['date']){if(messages[messageId]['username']){$('#siropuChatRoom-'+roomId+' .siropuChatMessages > li[data-author="'+messages[messageId]['username']+'"]').remove();}else{$('#siropuChatRoom-'+roomId+' .siropuChatMessages').html('');}}
if(chatLastMassage.length&&(messages[messageId]['user_id']==chatLastMassage.attr('data-userid')||chatLastMassage.find('.DateTime').data('time')<messages[messageId]['date'])){chatLastMassage.html('');}
break;case'delete':row.remove();break;case'edit':var message=messages[messageId]['message'];if(message&&message!=row.find('.siropuChatMessage').html()){row.find('.siropuChatMessage').html(message);}
break;}}}
if(data.messages[roomId]){var messagesContainer=$('#siropuChatRoom-'+roomId+' .siropuChatMessages');var messagesList=$(data.messages[roomId]);var messagesLastId=messagesContainer.attr('data-last-id');if(!window.chatRemoveDuplicates){messagesList=$.grep(messagesList,function(value){return messagesContainer.find('> li[id="'+value.id+'"]').length?false:true;});}
if(messagesLastId!=0){if(messagesContainer.find('> li').length>=window.chatWindowMassagesLimit){messagesContainer.find('> li:nth-child('+(inverse?'':'-')+'n+'+window.chatDatabaseMassagesLimit+')').remove();}
if(inverse){messagesContainer.prepend(messagesList);}else{messagesContainer.append(messagesList);}}else{messagesContainer.html(messagesList);}
if(window.chatRemoveDuplicates){chatRemoveDuplicates(messagesContainer);}
var roomLastId=chatGetLastId(messagesContainer,inverse);messagesContainer.attr('data-last-id',roomLastId);if(roomLastId!=data.lastFakeId){window.chatUserRooms[roomId]=roomLastId;}
if(!roomTab.hasClass('active')&&messagesLastId!=0&&data.prune==''){roomTab.addClass('roomNewMessage');}}
if(data.users[roomId]){$('#siropuChatRoom-'+roomId+' .siropuChatUsers').html(data.users[roomId]);window.chatUsersLastUpdate=data.lastUpdate;if(chatTabs.length){roomTab.find('b').attr('title',data.info[roomId].list).text('('+data.info[roomId].count+')');}
if($('.siropuChatUserMenu').length){$('.siropuChatUserMenu').each(function(){if(data.lastUpdate-$(this).data('time')>=15){$(this).remove();}});}}}
if(data.forumActivity.length){var forumActivity=$(data.forumActivity);var activityCurrentId=chatForumActivity.attr('data-last-id');forumActivity=$.grep(forumActivity,function(value){return chatForumActivity.find('> li[id="'+value.id+'"]').length?false:true;});if(activityCurrentId!=0){if(inverse){chatForumActivity.prepend(forumActivity);}else{chatForumActivity.append(forumActivity);}}else{chatForumActivity.html(forumActivity);}
var activityLastId=chatGetLastId($('#siropuChatForumActivity'),inverse);window.chatActivityLastId=activityLastId;window.chatActivityLastUpdate=data.lastUpdate;chatForumActivity.attr('data-last-id',activityLastId);if(!$('.tabRoomActivity').hasClass('active')&&activityCurrentId!=0&&activityCurrentId!=activityLastId){$('.tabRoomActivity').addClass('roomNewMessage');}}
if(data.lastRowMessage.length){chatLastMassage.html(data.lastRowMessage).attr({'data-room-id':data.lastRowRoomId,'data-message-id':data.lastRowMessageId,'data-userid':data.lastRowUserId});}
chatAutoscroll();chatElements.xfActivate();window.chatLastRoomId=data.lastRowRoomId;if(window.chatLastId&&data.lastId&&window.chatLastId!=data.lastId&&data.action!='join'){if(data.action=='refresh'&&data.notification.message!==undefined&&!chatPageFocus&&window.chatDesktopNotifications){chatDisplayNotification(data.notification);}
var chatSoundAlert=chatSoundNew;switch(data.playSound){case'whisper':chatSoundAlert=chatSoundWhisper;break;case'tagged':chatSoundAlert=chatSoundTagged;break;case'bot':chatSoundAlert=chatSoundBot;break;}
if(chatGetSoundSettings(data.playSound?data.playSound:'normal')){chatPlaySound(chatSoundAlert);}
if(!chatPageFocus&&window.chatNewMessageBlinkAlert&&data.lastRowUsername!=chat.data('user')){clearInterval(titleBlinkInterval);titleBlinkInterval=setInterval(function(){$('title').text($('title').text()==chatPageTitle?window.chatPhrases.new_message:chatPageTitle);},1500);}}
if(data.lastId&&data.lastId!=data.lastFakeId){window.chatLastId=data.lastId;}
if(data.userCount){chatToggle.find('span').text(data.userCount);$('.chat .itemCount .Total').text(data.userCount);}
if(window.chatNoticesLastUpdate<=data.lastUpdate-15){if($('#siropuChatNotice').length){if(data.notice){$('#siropuChatNoticeText').html(data.notice);}else{$('#siropuChatNotice').remove();}}else if(data.notice){$('#siropuChatHeader').after('<div id="siropuChatNotice"><div id="siropuChatNoticeText">'+data.notice+'</div></div>');}
window.chatNoticesLastUpdate=data.lastUpdate;}}
$('.siropuChatMessages, #siropuChatForumActivity').scroll(function(){if(window.chatToggleAutoscroll){return;}
$(this).attr('data-autoscroll',0);var $inverse=chatGetSettings('inverse');var $scrollDiff=$(this)[0].scrollHeight-$(this).innerHeight();var $scrollTop=parseInt($(this).scrollTop());if((($scrollTop==$scrollDiff||$scrollTop+1==$scrollDiff||$scrollTop-1==$scrollDiff)&&!$inverse)||$scrollTop==0&&$inverse){$(this).attr('data-autoscroll',1);}});function chatAutoscroll(room){var room=room?room:$('.siropuChatMessages:visible');if(room.attr('data-autoscroll')==1){chatDoAutoscroll(room);}}
function chatDoAutoscroll(room){if(chatGetSettings('inverse')){room.scrollTop(0);}else{room.scrollTop(1000000);}}
function chatMediaAutoscroll(){if($('.siropuChatMessage:visible .bbCodeImage, .siropuChatMessage:visible iframe').length){mediaForceAutoscroll=setInterval(function(){chatAutoscroll($('.siropuChatMessages:visible'));},1000);setTimeout(function(){clearInterval(mediaForceAutoscroll);},10000);}}
function chatLeaveRoomEvents(roomId){$('#siropuChatRoom-'+roomId+', .tabRoom-'+roomId).remove();delete window.chatUserRooms[roomId];if($('.siropuChatMessages').length){var lastRoom=$('#siropuChatTabs > li').not('.tabRoomActivity, .tabRooms').last();lastRoom.trigger('click');window.chatRoomId=lastRoom.data('room-id');}else{if($('.tabRoomActivity').length){$('.tabRoomActivity').trigger('click');}
window.chatRoomId=0;chat.attr('data-session',0);}}
function chatLeaveRoom(roomId){XenForo.ajax(chatAjaxURL+'roomsLeave',{room_id:roomId,user_rooms:window.chatUserRooms},function(){chatLeaveRoomEvents(roomId);},{error:false});}
function escapeRegExp(str){return isNaN(str)?str.replace(/[\-\[\]\/\{\}\(\)\*\+\?\.\\\^\$\|]/g,"\\$&"):str;}
if(window.chatToggleAutoscroll){$('#chatToggleAutoscroll').show();}
$('#chatToggleAutoscroll').click(function(){if($(this).attr('data-autoscroll')==1){$(this).attr('data-autoscroll',0).html('&#8597;');$('.siropuChatMessages').attr('data-autoscroll',0);}else{$(this).attr('data-autoscroll',1).html('&#8595;');$('.siropuChatMessages').attr('data-autoscroll',1);}});function chatPlaySound(sound){if(sound&&(chatPageFocus||!chat.hasClass('siropuChatAllPages'))){sound.play();}}
function chatWrapText(text,tag){return'['+tag+']'+text+'[/'+tag+']';}
function chatInsertBBCode(tag){var value=chatInput.val();var start=chatInput[0].selectionStart;var end=chatInput[0].selectionEnd;var textSelected=value.substring(start,end);var textWraped=chatWrapText(textSelected,tag);if(value&&value.substring(value.length-7)==chatWrapText('',tag)){chatInput.focus();return false;}
chatInput.val(value.substring(0,start)+textWraped+value.substring(end,value.length)).focus();startEnd=chatInput.val().length-4;chatInput[0].setSelectionRange(startEnd,startEnd);}
function chatChangeColor(){var chatSelectColor=$('#siropuChatSelectColor');if(chatSelectColor.length){chatSelectColor.find('label').css('color','#'+chatSelectColor.find('select').val());}}
function chatAdjustMaximizedHeight($force){var heightHeader=$('#siropuChatHeader').outerHeight(true);var heightNotice=$('#siropuChatNotice').outerHeight(true);var heightTabs=chatTabs.outerHeight(true);var heightEditor=chatEditor.outerHeight(true);var chatAdsHeight=0;$('.siropuChatAds').each(function(){if(!$(this).parents('#siropuChatEditor').length){chatAdsHeight+=$(this).outerHeight(true);}});if($('#siropuChatFull').length){chatContent.css({'top':heightHeader+heightNotice+heightTabs+chatAdsHeight+'px','bottom':heightEditor});}else if(chat.hasClass('siropuChatAllPages')){if(chat.hasClass('siropuChatMaximized')||$force){chatContent.css('height',chat.height()-heightEditor-heightHeader-heightTabs-heightNotice-chatAdsHeight+'px');}else{chatContent.removeAttr('style');}}}
function chatUpdateUserCount($count){if($count){chatToggle.find('span').text($count);$('.chat .itemCount .Total').text($count);}}
function chatGetRooms(){chatRooms.html('');XenForo.ajax(chatAjaxURL+'rooms-get',{},function(ajaxData){chatRooms.html(ajaxData.rooms).xfActivate();if($('#siropuChatRooms > li').length>5){chatInput.focus().val('/room ').focus();}},{error:false});}
function chatCloseOverlay($this){$this.find('.OverlayCloser').trigger('click');}
function chatGetMessages(loading){if(chatInput.is(':disabled')||!$('.siropuChatMessages').length){return;}
XenForo.ajax(chatAjaxURL+'refresh',{room_id:window.chatRoomId,user_rooms:window.chatUserRooms,last_id:window.chatLastId,activity_last_id:window.chatActivityLastId,activity_last_update:window.chatActivityLastUpdate,users_last_update:window.chatUsersLastUpdate,inverse:chatGetSettings('inverse'),hide_bot:chatGetSettings('hide_bot'),no_users:chatGetSettings('hide_chatters'),show_ignored:chatGetSettings('show_ignored'),all_pages:chatGetUint(chat.hasClass('siropuChatAllPages')),loading:loading?1:0,},function(ajaxData){if(window.chatKeepSessionAlive&&ajaxData.activeSession&&ajaxData.lastActive>=300){XenForo.ajax(chatAjaxURL+'update-session',{room_id:window.chatRoomId},function(ajaxData){},{global:false,error:false});}
if(!ajaxData.activeSession&&chat.attr('data-session')==1){chat.attr('data-session',0);clearInterval(chatRefreshInterval);chatInitRefreshInterval();}
chatUpdateRooms(ajaxData);if(loading){chatMediaAutoscroll();}},{global:false,error:false});}
chatMessages.each(function(){window.chatUserRooms[$(this).parent().data('room-id')]=$(this).data('last-id');});if(!chat.hasClass('siropuChatPage')){chatGetMessages(true);}
function chatInitRefreshInterval(){if(chat.attr('data-session')==1){if(chat.is(':visible')){chatRefreshInterval=setInterval(chatGetMessages,window.chatRefreshActiveVisible);}else{chatRefreshInterval=setInterval(chatGetMessages,window.chatRefreshActiveHidden);}}else{if(chat.is(':visible')){chatRefreshInterval=setInterval(chatGetMessages,window.chatRefreshInactiveVisible);}else{chatRefreshInterval=setInterval(chatGetMessages,window.chatRefreshInactiveHidden);}}}
chatInitRefreshInterval();chatChangeColor();chatMediaAutoscroll();chatLoadSounds($('#siropuChatSettings fieldset[data-type="sound"] input:checked').length);if(chat.hasClass('siropuChatPage')){chatAutoscroll();}
if($('#siropuChatFull').length){chatAdjustMaximizedHeight();}
if(chatGetSettings('disable_autohide')&&chatBar.length){setTimeout(function(){chatBar.trigger('click');},500);}
chatBar.click(function(e){chat.toggle();chatLastMassage.toggle();chatToggle.toggleClass('siropuChatActiveTab');clearInterval(chatRefreshInterval);chatInitRefreshInterval();if(chatTabs.length){chatSwitchTabs();}
if(window.matchMedia('(min-width: 768px)').matches){chatInput.focus();}
if(window.matchMedia('(max-width: 480px)').matches){if(chat.is(':hidden')&&chat.hasClass('siropuChatAllPages')){chatEditorBBCode.hide();}}
chatAdjustMaximizedHeight(chat.is(':hidden')?false:true);chatAutoscroll();});window.addEventListener('orientationchange',function(){chatAutoscroll();},false);window.addEventListener('resize',function(){chatAutoscroll();},false);$('#siropuChatNotice').dblclick(function(){$('#siropuChatEditNotices').trigger('click');});$(document).on('click','#siropuChat .bbCodeSpoilerButton',function(){setTimeout(function(){chatAutoscroll();},500);});chatToggle.click(function(e){e.preventDefault();});var chatFocus=false;$('#siropuChat, #siropuChatBar').mouseover(function(){chatFocus=true;}).mouseout(function(){chatFocus=false;});$(document).click(function(e){if(chat.is(':visible')&&!$('.xenOverlay:visible').length&&!$('.Menu:visible').length&&!chatFocus&&e.target.id!='siropuChatSubmit'&&e.target.className!='siropuChatMute'&&!e.target.className.match('tabRoom-')&&!chatGetSettings('disable_autohide')){chatBar.trigger('click');}});$(document).on('click','.siropuChatContentLeft > .username, .siropuChatTagAlt',function(e){e.preventDefault();var author=$(this).parents('li').data('author');if(author&&chat.data('user')!=author&&$(this).hasClass('Tooltip')&&!chatInput.val().match(escapeRegExp(author))){var tagData=chatInput.val()+'@'+author+', ';chatInput.focus().val(tagData).focus();}});$(document).on('click','.siropuChatWhisperAction',function(e){e.preventDefault();chatInput.focus();if(chatInput.length&&$(this).hasClass('Tooltip')&&$(this).parents('li').hasClass('siropuChatWhisperPolice')&&!confirm(chatPhrases.whisper_warning)){return false;}
if(($(this).hasClass('Tooltip')||!chatInput.val().match(/\/whisper/))&&chatInput.val().length){chatInput.val('');}
var username=$(this).data('username');var inputData=chatInput.val();if(!inputData.match(escapeRegExp(username))){if(inputData.match(/^\/whisper/)){chatInput.val(inputData.replace(']',', '+username+']')).focus();}else{chatInput.val('/whisper ['+username+'] ').focus();}}else{var newInput=inputData.replace(username,'').replace(', ','');chatInput.val(newInput.match(/\[\]/)?'':newInput).focus();}});$(document).on('click','.siropuChatQuote',function(e){e.preventDefault();XenForo.ajax($(this).attr('href'),{},function(ajaxData){if(ajaxData.quotedMessage&&ajaxData.quotedMessage!=chatInput.val().trim()){chatInput.val((chatInput.val()?chatInput.val()+' ':'')+ajaxData.quotedMessage+' ');}
chatInput.focus();},{global:false,error:false});});$(document).on('click','#siropuChatBBCode button',function(){var $this=$(this);var type=$this.data('type');var tag=$this.data('tag');switch(type){case'tag':chatInsertBBCode(tag);break;case'link':case'image':case'media':case'quote':case'spoiler':case'code':XenForo.ajax(chatAjaxURL+'media',{type:type,},function(ajaxData){XenForo.createOverlay(null,ajaxData.templateHtml,{noCache:true}).load();},{error:false});break;case'smilie':if($this.attr('data-loading')){return;}
if(!$('#siropuChatSmilies').length){$this.attr('data-loading',true);XenForo.ajax('index.php?editor/smilies',{},function(ajaxData){chatEditorBBCode.after($('<div id="siropuChatSmilies" />').html(ajaxData.templateHtml).hide()).xfActivate();$this.removeAttr('data-loading');$('#siropuChatSmilies').slideToggle().xfActivate();},{error:false});}
$('#siropuChatSmilies').slideToggle();setTimeout(function(){chatAdjustMaximizedHeight(true);},500);break;}});$(document).on('submit','#siropuChatMediaForm',function(e){e.preventDefault();var $this=$(this);var type=$this.data('type');var url=$this.find('input[name="url"]');var content=$this.find('textarea').val();var insert='';switch(type){case'link':case'image':uploads=$('#siropuChatImages:visible > li input:checked');if(!url.val()&&!uploads.length){url.focus();return false;}
if(uploads.length){uploads.each(function(){insert+=chatWrapText($(this).val(),(type=='link'?'URL':'IMG'));});}else{insert=chatWrapText(url.val(),(type=='link'?'URL':'IMG'));}
break;case'media':XenForo.ajax('index.php?editor/media',$this.serialize(),function(ajaxData){chatInput.val(chatInput.val()+ajaxData.matchBbCode).focus();},{error:false});break;case'quote':var name=$this.find('input[name="name"]').val();insert='[QUOTE'+(name?'='+name:'')+']'+(content?content:'')+'[/QUOTE]';break;case'spoiler':var title=$this.find('input[name="title"]').val();insert='[SPOILER'+(title?'='+title:'')+']'+(content?content:'')+'[/SPOILER]';break;case'code':insert=chatWrapText(content,$this.find('select').val());break;}
if(insert){chatInput.val(chatInput.val()+insert).focus();}
chatCloseOverlay($this);if($('#siropuChatMediaForm').attr('data-submit')){setTimeout(function(){chatSubmit.submit();chatDoAutoscroll($('#siropuChatRoom-'+roomId+' .siropuChatMessages'));},500);}
$('#siropuChatMediaForm').removeAttr('data-submit');});$(document).on('click','#siropuChatInsertSubmit',function(){$('#siropuChatMediaForm').attr('data-submit',true);});$(document).on('click','#siropuChatToggleRooms, .tabRooms',function(e){e.preventDefault();if(chatRooms.is(':hidden')){chatGetRooms();}else{chatInput.val('').focus();}
chatRooms.toggle();if(chatRooms.is(':visible')){$('#siropuChatContent > div, #siropuChatForumActivity').hide();}else if(chatTabs.length){$('#siropuChatRoom-'+chatTabs.find('> li.active').data('room-id')).show();}else{$('#siropuChatContent > div').show();}});$(document).on('click','#siropuChatSmilies .Smilie',function(){chatInput.val(chatInput.val()+' '+$(this).find('img').attr('alt')).focus();});$(document).on('click','#siropuChatToggleUsers',function(e){e.preventDefault();$('#siropuChatContent > div:visible .siropuChatUsers').toggle().xfActivate();});$(document).on('click','.siropuChatKick',function(e){e.preventDefault();XenForo.ajax(chatAjaxURL+'kick',{room_id:window.chatRoomId,user_id:$(this).data('user-id')},function(ajaxData){if(!XenForo.hasResponseError(ajaxData)){if(ajaxData.kicked){$('#siropuChatRoom-'+window.chatRoomId+' .siropuChatUsers > li[id="'+ajaxData.kicked+'"]').remove();}}else{chatPlaySound(chatSoundError);}},{global:false,error:false});});$(document).on('click','.siropuChatMute',function(e){e.preventDefault();var $this=$(this);XenForo.ajax(chatAjaxURL+'mute',{room_id:window.chatRoomId,user_id:$this.data('user-id')},function(ajaxData){if(!XenForo.hasResponseError(ajaxData)){if(ajaxData.muted){$this.remove();}}else{chatPlaySound(chatSoundError);}},{global:false,error:false});});$(document).on('click','.siropuChatLogout',function(e){e.preventDefault();chatLeaveRoom(window.chatRoomId);});if($('.siropuChatSidebar').length){$(document).on('click','.siropuChatMeta',function(){var actions=$(this).find('.siropuChatMessageActions');if(actions.find('li').length){$(this).find('.DateTime').hide();actions.css('display','inline-block');}});}else{$(document).on('mouseover mouseout','.siropuChatMessages > li, #siropuChatForumActivity > li',function(e){var time=$(this).find('.DateTime');var actions=$(this).find('.siropuChatMessageActions');if(actions.find('li').length){if(e.type=='mouseover'){time.hide();actions.css('display','inline-block');}else{time.show();actions.hide();}}});}
$('#siropuChatSettings input, #siropuChatSettings select').change(function(){var form=$(this).parents('form');var name=$(this).attr('name');switch(name){case'sound[normal]':case'sound[whisper]':case'sound[tagged]':case'sound[bot]':chatLoadSounds($(this).is(':checked'));break;case'maximized':chat.toggleClass('siropuChatMaximized');chatAdjustMaximizedHeight();chatAutoscroll();break;case'inverse':var elements=$('.siropuChatMessages, #siropuChatForumActivity');chatAutoscroll(elements);elements.attr('data-autoscroll',1);break;case'hide_bot':if($(this).is(':checked')){$('.siropuChatMessages').find('li.siropuChatBot').fadeOut();}else{$('.siropuChatMessages').find('li.siropuChatBot').fadeIn();}
break;case'hide_status':if($(this).is(':checked')){$('.siropuChatUsers .siropuChatUserStatus').fadeOut();}else{$('.siropuChatUsers .siropuChatUserStatus').fadeIn();}
break;case'color':chatChangeColor();break;case'hide_chatters':chat.toggleClass('siropuChatNoUsers');break;case'disabled':if(chatGetSettings('disabled')){$('#siropuChat, #siropuChatBar').fadeOut();}else{$('#siropuChat, #siropuChatBar').fadeIn();}
break;}
XenForo.ajax(chatAjaxURL+'settings',form.serialize(),function(ajaxData){if(name=='display_mode'&&!chat.hasClass('siropuChatPage')&&confirm(window.chatPhrases.action_reload)){location.reload();}
if(!chatSettings.attr('data-warning')){XenForo.hasResponseError(ajaxData);}
chatSettings.attr('data-warning',true)},{error:false});if(name=='editor_on_top'&&confirm(window.chatPhrases.action_reload)){location.reload();}});$(document).on('click','.siropuChatColorPicker input.save',function(){chatSettings.find('input[name="color"]').val($('.siropuChatColorPicker').find('input[name="remove"]').is(':checked')?'':$('.siropuChatColorPicker').find('#pctrl_h').val());XenForo.ajax(chatAjaxURL+'settings',chatSettings.serialize(),function(ajaxData){},{error:false});});chatInput.keyup(function(){var input=$(this).val();if(input.match(/^\/user/)&&$('#siropuChatRoom-'+window.chatRoomId).is(':visible')){var regex=new RegExp(input.replace('/user','').trim(),'gi');$('#siropuChatRoom-'+window.chatRoomId+' .siropuChatMessages > li').hide().each(function(){if($(this).data('author').match(regex)){$(this).show();}});}else if(input.match(/^\/room/)&&chatRooms.is(':visible')){var regex=new RegExp(input.replace('/room','').trim(),'gi');$('#siropuChatRooms > li').hide().each(function(){if($(this).data('name').match(regex)){$(this).show();}});}});chatInput.click(function(){if(chatEditorBBCode.is(':hidden')){chatEditorBBCode.fadeIn();chatAdjustMaximizedHeight(true);chatAutoscroll();}});$(document).on('click','#siropuChatTabs > li',function(){var roomId=$(this).data('room-id');var target=$(this).data('target');$(this).addClass('active').siblings().removeClass('active');$('#siropuChatContent > ol, #siropuChatContent > div, #siropuChatNoRoomsJoined').hide();$(target).show();if($(this).hasClass('roomNewMessage')){$(this).removeClass('roomNewMessage');}
if(roomId!==undefined){window.chatRoomId=roomId;if(window.chatLastActiveTabDefault){XenForo.ajax(chatAjaxURL+'set-default-room',{room_id:roomId},function(ajaxData){},{global:false,error:false});}
if(window.matchMedia('(min-width: 768px)').matches){chatInput.focus();}
chatDoAutoscroll($('#siropuChatRoom-'+roomId+' .siropuChatMessages'));}
if(target=='#siropuChatForumActivity'){chatDoAutoscroll($(target));}});$(document).on('dblclick','#siropuChatTabs > li',function(){var roomId=$(this).data('room-id');if(roomId===undefined){return;}
chatLeaveRoom(roomId);});$(document).on('submit','#siropuChatRoomDelete',function(e){e.preventDefault();var $this=$(this);XenForo.ajax(chatAjaxURL+'rooms/delete',$(this).serialize(),function(ajaxData){if(!XenForo.hasResponseError(ajaxData)){if(ajaxData.roomId){chatRooms.find('li[id="'+ajaxData.roomId+'"]').fadeOut();if($('.tabRoom-'+ajaxData.roomId).length){$('.tabRoom-'+ajaxData.roomId).remove();}}
chatCloseOverlay($this);}},{global:false,error:false});});$(document).on('submit','#siropuChatRoomAdd',function(e){e.preventDefault();var $this=$(this);XenForo.ajax(chatAjaxURL+'rooms/save',$this.serialize(),function(ajaxData){if(!XenForo.hasResponseError(ajaxData)){if(ajaxData.roomAdded){if(chatRooms.is(':hidden')){chatToggleRooms.trigger('click');}else{chatGetRooms();}
chatCloseOverlay($this);}}else{chatPlaySound(chatSoundError);}});});$(document).on('click','.siropuChatRoomName',function(){$(this).parents('li').find('form').trigger('submit');});$(document).on('submit','.siropuChatRoomActions form',function(e){e.preventDefault();var $this=$(this);var $roomId=$this.find('input[name="room_id"]').val();var $roomName=$this.parents('li').data('name');var $password=$this.find('input[name="password"]');var $button=$this.find('button');if($password.length&&!$password.val().trim()){$password.toggle().css('right',$(this).find('button').outerWidth()).focus();return;}
if($('#siropuChatRoom-'+$roomId).length){if($('.tabRoom-'+$roomId).length){chatSwitchTabs($roomId);}else{chatToggleRooms.trigger('click');}
return;}
clearInterval(chatRefreshInterval);$button.prop('disabled',true);rooms=window.chatUserRooms;rooms[$roomId]=0;XenForo.ajax(chatAjaxURL+'rooms/join',{room_id:$roomId,user_rooms:rooms,password:$password.val(),activity_last_id:window.chatActivityLastId,inverse:chatGetSettings('inverse'),hide_bot:chatGetSettings('hide_bot'),no_users:chatGetSettings('hide_chatters'),show_ignored:chatGetSettings('show_ignored')},function(ajaxData){if(!XenForo.hasResponseError(ajaxData)){if(!window.chatJoinMultipleRooms){delete window.chatUserRooms[window.chatRoomId];}
window.chatRoomId=$roomId;window.chatUserRooms[$roomId]=0;chatRooms.toggle();var newRoom='<div id="siropuChatRoom-'+$roomId+'" data-room-id="'+$roomId+'"><ol class="siropuChatUsers"></ol><ol class="siropuChatMessages" data-last-id="0" data-autoscroll="1"></ol></div>';if(chatTabs.length){var newTab='<li class="tabRoom-'+$roomId+' active" data-target="#siropuChatRoom-'+$roomId+'" data-room-id="'+$roomId+'"><a>'+$roomName+' <b class="muted" title="">[1]</b></a></li>';if($('.tabRoomActivity').length){$('.tabRoomActivity').before(newTab);}else if($('.tabRooms').length){$('.tabRooms').before(newTab);}else{chatTabs.append(newTab);}
chatContent.append(newRoom);chatSwitchTabs($roomId);if(chatNoRoomsJoined.length){chatNoRoomsJoined.remove();}}else{$('#siropuChatContent > div').remove();chatContent.append(newRoom);}
chatUpdateRooms(ajaxData);chatDoAutoscroll($('.siropuChatMessages:visible'));if(chat.attr('data-session')==0){chat.attr('data-session',1);}
clearInterval(chatRefreshInterval);chatInitRefreshInterval();$('#siropuChatHeader h3 span').text(' - '+$roomName);chatInput.val('').focus();if($('#siropuChatBannedMessage').length){if(confirm(window.chatPhrases.reload_page)){location.reload();}}}else{chatPlaySound(chatSoundError);}
$button.prop('disabled',false);},{error:false});});function chatFormToggleDisabled(state){if(state){chatInput.prop('disabled',true).val('').attr('placeholder',window.chatPhrases.please_wait);chatSubmit.prop('disabled',true).addClass('disabled');}else{chatInput.prop('disabled',false).attr('placeholder',window.chatPhrases.write_message).focus();chatSubmit.prop('disabled',false).removeClass('disabled');}}
$(document).on('submit','#siropuChatEditor form',function(e){e.preventDefault();var roomId=window.chatRoomId;var message=chatInput.val().trim();var placeholder=chatInput.attr('placeholder');if(chatInput.is(':disabled')||!$('.siropuChatMessages').length){return;}
if(!message){chatInput.focus();return;}
if(message.match(/^\/clear/)){$('#siropuChatRoom-'+roomId+' .siropuChatMessages').html('');chatInput.val('').focus();return;}
if(message.match(/^\/help/)||message.match(/^\/rules/)){if(message.match(/^\/help/)){if($('#siropuChatHelp').length){$('#siropuChatHelp').trigger('click');return;}
action='help';}else{if($('#siropuChatRules').length){$('#siropuChatRules').trigger('click');return;}
action='rules';}
XenForo.ajax(chatAjaxURL+action,{},function(ajaxData){XenForo.createOverlay(null,ajaxData.templateHtml,{title:ajaxData.title,fixed:false,className:'siropuChatHelp'}).load();chatInput.val('').focus();},{error:false});return;}
if(message.match(/^\/rooms/)){chatInput.val('').focus();chatToggleRooms.trigger('click');return;}
if(message.match(/^(\/quit|\/leave)/)){var quit=true;}else{var quit=false;}
if($('.tabRoomActivity, .tabRooms').hasClass('active')&&!message.match(/^\/prune forum/)){chatSwitchTabs(roomId);}
chatFormToggleDisabled(true);clearInterval(chatRefreshInterval);var chatResponseTimeout=setTimeout(function(){if(chatInput.is(':disabled')){chatFormToggleDisabled(false);chatInput.attr('placeholder',window.chatPhrases.no_response);}},10000);XenForo.ajax(chatAjaxURL+'submit',{message:message,room_id:roomId,user_rooms:window.chatUserRooms,last_id:window.chatLastId,activity_last_id:window.chatActivityLastId,activity_last_update:window.chatActivityLastUpdate,users_last_update:window.chatUsersLastUpdate,session_last_update:chatSessionLastUpdate,inverse:chatGetSettings('inverse'),hide_bot:chatGetSettings('hide_bot'),no_users:chatGetSettings('hide_chatters'),show_ignored:chatGetSettings('show_ignored'),all_pages:chatGetUint(chat.hasClass('siropuChatAllPages'))},function(ajaxData){if(!XenForo.hasResponseError(ajaxData)){if(quit){chatLeaveRoomEvents(roomId);if($('.siropuChatMessages').length){chat.attr('data-session',0);}}
var roomContainer=$('#siropuChatRoom-'+roomId);if(ajaxData.prune){switch(ajaxData.prune){case'all':chatMessages.html('');break;case'room':roomContainer.find('.siropuChatMessages').html('');break;case'forum':if(chatForumActivity.length){chatForumActivity.html('');}else{$('.siropuChatForumActivityBot').remove();}
break;default:roomContainer.find('.siropuChatMessages > li[data-author="'+ajaxData.prune+'"]').remove();break;}}
chatUpdateRooms(ajaxData);if(message.match(/^(\/giphy|\/g)/)){setTimeout(function(){chatAutoscroll();},1000);}
if(chat.attr('data-session')==0&&!quit){chat.attr('data-session',1);}
if(ajaxData.kick){roomContainer.find('.siropuChatUsers> li[id="'+ajaxData.kick+'"]').remove();}
if(ajaxData.sessionUpdate){chatSessionLastUpdate=ajaxData.lastUpdate;}
if(!message.match(/^(\/whisper|\/w|\/status|\/s|\/kick|\/me|\/quit|\/leave|\/giphy|\/g)/)){message=message.replace(/\[(.+?)\](.*)\[\/(.+?)\]/,"$2");var responses=window.chatResponses;for(var key in responses){if(message.match(new RegExp('(\\W|^)'+escapeRegExp(key)+'(\\W|$)','gi'))){var type=responses[key].type;var rooms=responses[key].rooms;if(type==1&&key!=message.toLowerCase()){continue;}else if(rooms.length==0||$.inArray(roomId.toString(),rooms)!=-1){XenForo.ajax(chatAjaxURL+'response',{room_id:roomId,response_id:responses[key].id},function(ajaxData){},{global:false,error:false});break;}}}}}else if(ajaxData.error!==undefined){chatPlaySound(chatSoundError);}
chatFormToggleDisabled(false);clearTimeout(chatResponseTimeout);chatInitRefreshInterval();},{global:false,error:false});});});}
(jQuery,this,document);