!function($,window,document,_undefined){var chatAjaxURL='index.php?chat/';var chatSoundError=new Audio('styles/Siropu/Chat/sounds/error.mp3');function chatCloseOverlay($this){$this.find('.OverlayCloser').trigger('click');}
$(document).on('submit','#siropuChatMessageEdit',function(e){e.preventDefault();var $this=$(this);if(!$this.find('textarea').val().trim()){$this.focus();return false;}
XenForo.ajax(chatAjaxURL+'edit',$this.serialize(),function(ajaxData){if(!XenForo.hasResponseError(ajaxData)){if(ajaxData.messageEdited){var elem=$('#siropuChatRoom-'+ajaxData.messageRoomId+' .siropuChatMessages');if($('.siropuChatArchive').length){elem=$('.siropuChatMessages');}
elem.find('li[id="'+ajaxData.messageId+'"] .siropuChatMessage').html(ajaxData.messageEdited).xfActivate();chatCloseOverlay($this);}}else{chatSoundError.play();}},{global:false,error:false});});$(document).on('submit','#siropuChatMessageDelete',function(e){e.preventDefault();var $this=$(this);XenForo.ajax(chatAjaxURL+'delete',$this.serialize(),function(ajaxData){if(!XenForo.hasResponseError(ajaxData)){if(ajaxData.messageId){if($('.tabRoomActivity').hasClass('active')){var elem=$('#siropuChatForumActivity');}else if($('.siropuChatArchive').length){var elem=$('.siropuChatMessages');}else{var elem=$('#siropuChatRoom-'+ajaxData.messageRoomId+' .siropuChatMessages');}
elem.find('li[id="'+ajaxData.messageId+'"]').fadeOut();chatCloseOverlay($this);}}else{chatSoundError.play();}},{global:false,error:false});});$(document).on('submit','#siropuChatMessageReport',function(e){e.preventDefault();var $this=$(this);XenForo.ajax(chatAjaxURL+'report',$this.serialize(),function(ajaxData){if(!XenForo.hasResponseError(ajaxData)){if(ajaxData.messageId){var elem=$('#siropuChatRoom-'+ajaxData.messageRoomId+' .siropuChatMessages');if($('.siropuChatArchive').length){elem=$('.siropuChatMessages');}
elem.find('li[id="'+ajaxData.messageId+'"]').css('opacity','0.5');chatCloseOverlay($this);}}},{global:false,error:false});});$(document).on('submit','#siropuChatReportDelete',function(e){e.preventDefault();var $this=$(this);XenForo.ajax(chatAjaxURL+'reports/delete',$this.serialize(),function(ajaxData){if(!XenForo.hasResponseError(ajaxData)){if(ajaxData.reportId){$('#siropuChatReports').find('tr[id="'+ajaxData.reportId+'"]').remove();if($('#siropuChatReports tr').length==1){location.reload();}else if($('.siropu_chat_report_view').length){window.location.replace($('base').attr('href')+'chat/reports');}
chatCloseOverlay($this);}}},{global:false,error:false});});$(document).on('submit','#siropuChatBan, #siropuChatUnBan',function(e){e.preventDefault();var $this=$(this);XenForo.ajax($this.attr('action'),$this.serialize(),function(ajaxData){if(!XenForo.hasResponseError(ajaxData)){if(ajaxData.userId!=''){if(ajaxData.banId){$('table#siropuChatUsers').find('tr[id="'+ajaxData.banId+'"]').remove();}else{$('#siropuChatRoom-'+ajaxData.roomId+' .siropuChatUsers').find('li[id="'+ajaxData.userId+'"]').remove();}
if($('#siropuChatUsers tr').length==1){location.reload();}
chatCloseOverlay($this);}}else{chatSoundError.play();}},{global:false,error:false});});$(document).on('submit','#siropuChatSaveNotices',function(e){e.preventDefault();var $this=$(this);XenForo.ajax(chatAjaxURL+'notices',$this.serialize(),function(ajaxData){if(ajaxData.notice){if($('#siropuChatNotice').length){$('#siropuChatNoticeText').html(ajaxData.notice).xfActivate();}else{$('#siropuChatHeader').after('<div id="siropuChatNotice"><div id="siropuChatNoticeText">'+ajaxData.notice+'</div></div>');}}else{$('#siropuChatNotice').remove();}
chatCloseOverlay($this);},{global:false,error:false});});}(jQuery,this,document);