/* Copyright (c) 2014 Brivium (http://brivium.com)
 * Author: Brivium
 * Addon: ModernStatistic
 * Version: 2.6.1
 * Released under the Brivium License Agreement: http://brivium.com/pages/terms-of-use/
 */

!function(c,m,n,p){XenForo.BRMSContainer=function(a){this.__construct(a)};XenForo.BRMSContainer.prototype={__construct:function(a){this.$container=a;var b=a.attr("data-previewType"),d=parseInt(a.attr("data-allowCusItemLimit")),f=parseInt(a.attr("data-allowCusLayout")),h=a.attr("data-useLimit"),k=a.attr("data-entryLimit"),e=a.attr("data-navPosition"),l=parseInt(a.attr("data-updateInterval")),g=parseInt(a.attr("data-modernStatisticId"));this.$containerClass="BRMSContainer ";a.hasClass("BRMSContainerDark")&&
(this.$containerClass="BRMSContainer BRMSContainerDark ");this.$previewType=b;this.$allowCusItemLimit=d;this.$allowCusLayout=f;this.$entryLimit=k;this.$navPosition=e;this.$updateIntervalTime=l;this.$modernStatisticId=g;this.$hardReload=!1;b=c.cookie("brmsLayoutChange"+g);f&&b&&(a.hasClass(b)||a.attr("class",this.$containerClass+b));h&&0<parseInt(h)?(this.$entryLimit=h,a.attr("data-entryLimit",h)):this.$allowCusItemLimit&&c.cookie("brmsNumberEntry"+g)&&(this.$entryLimit=c.cookie("brmsNumberEntry"+
g),a.attr("data-entryLimit",c.cookie("brmsNumberEntry"+g)));f=a.find("ul.brmsTabNav > li").length-2;a.find("ul.brmsTabNav > li:first").addClass("first");a.find("ul.brmsTabNav > li:eq("+f+")").addClass("last");a.find("ul.brmsTabNav > li > a, .brmsTabNavHidden  ul.brmsDropdownMenu  > li > a").click(c.context(this,"navTabTriggerHandle"));this.showTab(a.find(".brmsTabContent:first").data("content"));this.updateInterval();a.find(".brmsNumberEntry").click(c.context(this,"numberEntryChangeHandle"));a.find(".brmsLayoutChange").click(c.context(this,
"layoutChangeHandle"));a.find(".brmsRefresh").click(c.context(this,"refreshHandle"));this.responsiveInit();c(m).resize(c.context(this,"responsiveInit"));a.find(".brmsDropdownToggle").hover(function(b){b=c(this).find("ul.brmsDropdownMenu");b.show();b.offset().left+b.width()>a.width()?b.addClass("edge"):b.removeClass("edge");"none"!=b.css("display")&&0>=b.offset().left&&b.css({left:0})},function(b){b=c(this).find("ul.brmsDropdownMenu");c(this).find("ul.brmsDropdownMenu").hide();b.offset().left+b.width()>
a.width()?b.addClass("edge"):b.removeClass("edge");"none"!=b.css("display")&&0>=b.offset().left&&b.css({left:0})});a.find(".brmsDropdownToggle").click(function(a){c(this).find("ul.brmsDropdownMenu").toggle()})},navTabTriggerHandle:function(a){var b=this.$container,d=c(a.target);d.attr("data-content")||(d=d.closest("a"));var f=d.closest("li");f&&!f.hasClass("current")&&(b.find("ul.brmsTabNav > li , .brmsTabNavHidden  ul.brmsDropdownMenu  > li").removeClass("current"),d.closest("li").addClass("current"),
f=d.attr("data-content"),b.find("."+f).find(".brmsIcoLoader").length&&this.getStatistics(d.attr("data-tabid"),0),b.find(".brmsTabContent").hide().removeClass("current"),b.find("."+f).fadeIn(100).addClass("current"),this.responsiveInit());a.preventDefault()},numberEntryChangeHandle:function(a){var b=this.$container,d=c(a.target).attr("data-limit");d&&(this.$entryLimit=d,b.attr("data-entryLimit",d),c.cookie("brmsNumberEntry"+this.$modernStatisticId,d),this.resetInterval(),this.$hardReload=1,this.runInterval(),
this.$hardReload=!1);a.preventDefault()},layoutChangeHandle:function(a){var b=this.$container,d=c(a.target).attr("data-layout");d&&(b.hasClass(d)||b.attr("class",this.$containerClass+d),c.cookie("brmsLayoutChange"+this.$modernStatisticId,d),this.responsiveInit());a.preventDefault()},refreshHandle:function(a){var b=c(a.target);b.hasClass("disable")||(this.resetInterval(),this.$hardReload=1,b.addClass("disable"),this.runInterval(),this.$hardReload=!1);a.preventDefault()},getStatistics:function(a,b){var d=
this.$container,f=this.$modernStatisticId;b||(b=this.$entryLimit);(d=(d.attr("data-loadUrl"),d.attr("data-loadUrl")))||(d="index.php?brms-statistic/statistics.json");XenForo.ajax(d,{tab_id:a,modern_statistic_id:f,hard_reload:this.$hardReload,limit:b},c.context(this,"showResult"),{cache:!1})},showResult:function(a){var b=this.$container;if(!1!==XenForo.hasResponseError(a))return!0;var c=b.find(".brmsTabContent_"+a.tabId);a.tabContentHtml?c.html(a.tabContentHtml):c.html("");console.log("Mordern Statistic Loaded");
a.limit&&(b.attr("data-entryLimit",a.limit),this.$entryLimit=a.limit);b.xfActivate();b.find(".brmsRefresh").removeClass("disable");this.responsiveInit()},showTab:function(a){var b=this.$container;a?(b.find("ul.brmsTabNav > li > a[data-content='"+a+"']").trigger("click"),a.replace("brmsTabContent_","")):(b.find("ul.brmsTabNav > li.current a").trigger("click"),b.find("ul.brmsTabNav > li.current a").attr("data-content").replace("brmsTabContent_",""))},runInterval:function(){this.getStatistics(this.$container.find("li.brmlShow.current a").data("tabid"),
this.$entryLimit)},updateInterval:function(){if(!this.$brmsActive){var a=this.$container,b=this.$updateIntervalTime,c=this;if(0<b)return this.$brmsActive=m.setInterval(function(){console.log("Mordern Statistic Update "+b+"s");c.getStatistics(a.find("ul.brmsTabNav > li.current a").data("tabid"),c.$entryLimit)},1E3*b)}},clearInterval:function(){m.clearInterval(this.$brmsActive);this.$brmsActive=!1;this.$updateIntervalTime=0},resetInterval:function(){this.clearInterval();this.updateInterval()},responsiveInit:function(){var a=
this.$container,b=a.find(".brmsLayoutList");if(a.hasClass("brmsTopTabs")){var d=0,f=a.find(".brmsStatisticHeader").width()-a.find(".brmsConfigList").width()-75,h=!1;a.find(".brmsTabNav > li.brmlShow").each(function(){var b=a.find(".brmsTabNavHidden li:eq("+c(this).index()+")");d+c(this).width()<=f?(d+=c(this).width(),c(this).css({display:"block"}),b.hasClass("current")&&(c(this).addClass("current"),b.removeClass("current")),b.css({display:"none"})):(h=!0,c(this).css({display:"none"}),c(this).hasClass("current")&&
(c(this).removeClass("current"),b.addClass("current")),b.css({display:"block"}))});var k=a.find(".brmsTabNavHiddenMenu");h?k.show():k.hide();480<a.width()?(c.cookie("brmsLayoutChange"+this.$modernStatisticId)&&!a.hasClass(c.cookie("brmsLayoutChange"+this.$modernStatisticId))&&a.attr("class",this.$containerClass+c.cookie("brmsLayoutChange"+this.$modernStatisticId)),b.css({display:"inline-block"})):b.css({display:"none"})}else 480>=a.width()&&(a.attr("class",this.$containerClass+" brmsTopTabs"),b.css({display:"none"}));
var e=a.find(".brmsTabContent.current ol li.itemStast");550>a.find(".brmsTabContent.current").width()?e.hasClass("itemUser")?(e.find(".itemDetail.itemSubDetail").hide(),e.find(".itemTitle").css({"max-width":"75%"}),350>a.find(".brmsTabContent.current").width()?(e.find(".itemDetail.itemDetailMain span").hide(),e.find(".itemDetail.itemDetailMain").css({width:"50px"}),e.find(".itemDetail.itemDetailMain.itemDate").css({width:"90px"}),e.find(".itemTitle").css({"max-width":"85%"})):(e.find(".itemDetail.itemDetailMain span, .itemDetail.itemDetailMain strong").show(),
e.find(".itemDetail.itemDetailMain").css({width:"200px"}),e.find(".itemTitle").css({"max-width":"75%"}))):(e.find(".itemDetail").hide(),e.find(".itemTitle").css({"max-width":"90%"}),350>a.find(".brmsTabContent.current").width()?e.find(".prefix").hide():e.find(".prefix").show()):(e.find(".prefix").show(),e.find(".itemDetail").show(),e.find(".itemTitle").css({width:"auto"}),e.find(".itemDetail.itemDetailMain span").show(),e.find(".itemDetail.itemDetailMain").css({width:"150px"}),e.find(".itemDetail.itemDetailMain.itemDate").css({width:"200px"}));
var l=parseInt(.33*e.width()),g=e.find(".itemTitle").width();e.find(".itemSubDetail").each(function(a){"none"==c(this).css("display")?g-150>l&&e.find(".itemSubDetail:eq("+a+")").show():g<l&&e.find(".itemSubDetail:eq("+a+")").hide()})},getText:function(a,b){return BRMSLANG.xf[a]||b}};XenForo.BRMSToolTip=function(a){this.__construct(a)};XenForo.BRMSToolTip.prototype={__construct:function(a){this.$item=a.find(".itemTitle > a");a.hover(c.context(this,"showTooltip"),c.context(this,"hideTooltip"));this.$listItem=
a},showTooltip:function(){this.$toolTip=c(this.toolTips(this.$item));c(this.toolTips(this.$item)).show().insertBefore(this.$item)},hideTooltip:function(){this.$listItem.find(".brmsToolTips").remove()},toolTips:function(a){if("resource"==a.attr("data-kind")&&a.attr("data-box"))return'<div class="xenTooltip brmsToolTips"><div>['+this.getText("category")+"] : <b>"+a.attr("data-box")+"</b></div><div>["+this.getText("download")+"] : <b>"+a.attr("data-download")+"</b> - ["+this.getText("update")+"] : <b>"+
a.attr("data-update")+"</b> - ["+this.getText("review")+"] : <b>"+a.attr("data-review")+"</b> - ["+this.getText("all_time_rating")+"] : <b>"+a.attr("data-vote")+'</b></div><span class="arrow"></span></div>';if(a.attr("data-box"))return'<div class="xenTooltip brmsToolTips"><div>['+this.getText("forum")+"] : <b>"+a.attr("data-box")+"</b></div><div>["+this.getText("views")+"] : <b>"+a.attr("data-view")+"</b> - ["+this.getText("replies")+"] : <b>"+a.attr("data-rep")+"</b> - ["+this.getText("likes")+"] : <b>"+
a.attr("data-like")+'</b></div><span class="arrow"></span></div>'},getText:function(a,b){return BRMSLANG.xf[a]||b}};XenForo.register(".BRMSContainer","XenForo.BRMSContainer");XenForo.register(".BRMSToolTip","XenForo.BRMSToolTip")}(jQuery,this,document);